version: '3'

services:
  redis:
    image: redis:4-alpine
    container_name: redis.{name}.prod
    command: 'redis-server --save "" --appendonly no'
    stdin_open: true
    tty: true
    networks:
      - global
    restart: always

  mysql:
    image: mariadb:10
    container_name: mysql.{name}.prod
    stdin_open: true
    tty: true
    networks:
      - global
    env_file:
       - ./docker/mysql/config.env
    volumes:
       - ~/data/mysql.{name}.prod:/var/lib/mysql
    restart: always

  php:
    image: amsdard.io/{name}/php:1.0
    container_name: php.{name}.prod
    networks:
      - global
    stdin_open: true
    tty: true
    env_file:
       - ./docker/php/config.env
    links:
       - mysql
       - redis
    restart: always

  nginx:
    image: amsdard.io/{name}/nginx:1.0
    container_name: nginx.{name}.prod
    networks:
      - global
    stdin_open: true
    tty: true
    labels:
       traefik.frontend.rule: "Host:{subdomain}.{name}.prod,{name}.prod"
    links:
       - php
    restart: always

networks:
  global:
    external: true
